3 module
js-tasks-ru/jsbasic-20230302_algaeminor pull request #3
Opened 2023-03-27 20:05 UTC by mikheyeva

2023-03-27 20:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-28 12:21 UTC, SinimaWath requested changes

2023-03-28 12:21 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
давай этот цикл попробуем заменить на map

2023-03-28 12:21 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }
этот цикл можно заменить на: `map().join('\n')`

2023-03-29 20:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-29 20:35 UTC, mikheyeva commented on 3-module/3-task/index.js
> +  }
сделала

2023-03-29 20:35 UTC, mikheyeva commented on 3-module/4-task/index.js
> +  }
сделала

2023-04-03 09:01 UTC, SinimaWath approved these changes

2023-04-03 09:02 UTC, merged